import { reactive } from 'vue'

export const globalState = reactive({
  token: ' ',
  userInfo: {
    avatar: 'https://s3.amazonaws.com/kmpz-p/images/i509728-1383698697750786442.jpg',
    name: 'Ronaldo John',
    balance: '$340.50',
    availableBalance: '$350.00',
  },
  paginationData: {
    totalPages: 6,
    currentPage: 1,
    limit: 15,
  },
  tableDataActive: {
    heads: [
      {
        name: 'Type',
        key: 'type',
        type: 'text',
      },
      {
        name: 'Location Type',
        key: 'locationType',
        type: 'text',
      },
      {
        name: 'Online Link',
        key: 'onlineLink',
        type: 'link',
      },
      {
        name: 'Post Data',
        key: 'postDate',
        type: 'text',
      },
      {
        name: 'Close Date',
        key: 'closeDate',
        type: 'text',
      },
      {
        name: 'Status',
        key: 'status',
        type: 'text',
      },
      {
        name: 'Actions',
        key: 'actions',
        type: 'actions',
      },
    ],
    rows: [
      {
        type: 'Local Client',
        locationType: 'Location Type',
        onlineLink: 'https://picsum.photos/200',
        postDate: '17-Apr-2020',
        closeDate: '17-Apr-2022',
        status: 'Active',
      },
      {
        type: 'Local Client',
        locationType: 'Location Type',
        onlineLink: 'https://picsum.photos/200',
        postDate: '17-Apr-2020',
        closeDate: '17-Apr-2022',
        status: 'Active',
      },
      {
        type: 'Local Client',
        locationType: 'Location Type',
        onlineLink: 'https://picsum.photos/200',
        postDate: '17-Apr-2020',
        closeDate: '17-Apr-2022',
        status: 'Active',
      },
      {
        type: 'Local Client',
        locationType: 'Location Type',
        onlineLink: 'https://picsum.photos/200',
        postDate: '17-Apr-2020',
        closeDate: '17-Apr-2022',
        status: 'Active',
      },
      {
        type: 'Local Client',
        locationType: 'Location Type',
        onlineLink: 'https://picsum.photos/200',
        postDate: '17-Apr-2020',
        closeDate: '17-Apr-2022',
        status: 'Active',
      },
    ],
  },
  tableDataPlanned: {
    heads: [
      {
        name: 'Privacy Type',
        key: 'privacyType',
        type: 'text',
      },
      {
        name: 'Event Start Date',
        key: 'eventStartDate',
        type: 'text',
      },
      {
        name: 'Event End Date',
        key: 'eventEndDate',
        type: 'text',
      },
      {
        name: 'Voucher Start Date',
        key: 'voucherStartDate',
        type: 'text',
      },
      {
        name: 'Voucher Exp Date',
        key: 'voucherExpDate',
        type: 'text',
      },
      {
        name: 'Redemption Information',
        key: 'redemptionInformation',
        type: 'text',
      },
      {
        name: 'Validation Type',
        key: 'validationType',
        type: 'text',
      },
      {
        name: 'Validation Value',
        key: 'validationValue',
        type: 'text',
      },
      {
        name: 'Hidden Details',
        key: 'hiddenDetails',
        type: 'text',
      },
      {
        name: 'Attributes',
        key: 'attributes',
        type: 'text',
      },
      {
        name: 'Issue Redeemable',
        key: 'issueRedeemable',
        type: 'checkbox',
      },
      {
        name: 'Add Featured Image',
        key: 'addFeaturedImage',
        type: 'button',
      },
      {
        name: 'Actions',
        key: 'actions',
        type: 'actions',
      },
    ],
    rows: [
      {
        privacyType: 'Privacy Type',
        eventStartDate: '17-Apr-2020',
        eventEndDate: '17-Apr-2022',
        voucherStartDate: '17-Apr-2020',
        voucherExpDate: '17-Apr-2022',
        redemptionInformation: 'Lorem Ipsum is simply text of the printing simply text',
        validationType: 'Validation Type',
        validationValue: '08',
        hiddenDetails: 'Lorem Ipsum is simply text of the printing simply text Ipsum is simply text of the printing simply text',
        attributes: 'Active',
        issueRedeemable: true,
        addFeaturedImage: 'View Image',
      },
      {
        privacyType: 'Privacy Type',
        eventStartDate: '17-Apr-2020',
        eventEndDate: '17-Apr-2022',
        voucherStartDate: '17-Apr-2020',
        voucherExpDate: '17-Apr-2022',
        redemptionInformation: 'Lorem Ipsum is simply text of the printing simply text',
        validationType: 'Validation Type',
        validationValue: '08',
        hiddenDetails: 'Lorem Ipsum is simply text of the printing simply text Ipsum is simply text of the printing simply text',
        attributes: 'Active',
        issueRedeemable: true,
        addFeaturedImage: 'View Image',
      },
      {
        privacyType: 'Privacy Type',
        eventStartDate: '17-Apr-2020',
        eventEndDate: '17-Apr-2022',
        voucherStartDate: '17-Apr-2020',
        voucherExpDate: '17-Apr-2022',
        redemptionInformation: 'Lorem Ipsum is simply text of the printing simply text',
        validationType: 'Validation Type',
        validationValue: '08',
        hiddenDetails: 'Lorem Ipsum is simply text of the printing simply text Ipsum is simply text of the printing simply text',
        attributes: 'Active',
        issueRedeemable: true,
        addFeaturedImage: 'View Image',
      },
      {
        privacyType: 'Privacy Type',
        eventStartDate: '17-Apr-2020',
        eventEndDate: '17-Apr-2022',
        voucherStartDate: '17-Apr-2020',
        voucherExpDate: '17-Apr-2022',
        redemptionInformation: 'Lorem Ipsum is simply text of the printing simply text',
        validationType: 'Validation Type',
        validationValue: '08',
        hiddenDetails: 'Lorem Ipsum is simply text of the printing simply text Ipsum is simply text of the printing simply text',
        attributes: 'Active',
        issueRedeemable: true,
        addFeaturedImage: 'View Image',
      },
    ],
  },
  tableDataPast: {
    heads: [
      {
        name: 'Name',
        key: 'name',
        type: 'text',
      },
      {
        name: 'Description',
        key: 'description',
        type: 'text',
      },
      {
        name: 'Price',
        key: 'price',
        type: 'text',
      },
      {
        name: 'Min Member',
        key: 'minMember',
        type: 'text',
      },
      {
        name: 'Max Member',
        key: 'maxMember',
        type: 'text',
      },
      {
        name: 'Limit',
        key: 'limit',
        type: 'text',
      },
      {
        name: 'Actions',
        key: 'actions',
        type: 'actions',
      },
    ],
    rows: [
      {
        name: 'Privacy Type',
        description: '17-Apr-2020',
        price: '17-Apr-2022',
        minMember: '17-Apr-2020',
        maxMember: '17-Apr-2022',
        limit: 'Lorem Ipsum is simply text of the printing simply text',
      },
      {
        name: 'Privacy Type',
        description: '17-Apr-2020',
        price: '17-Apr-2022',
        minMember: '17-Apr-2020',
        maxMember: '17-Apr-2022',
        limit: 'Lorem Ipsum is simply text of the printing simply text',
      },
      {
        name: 'Privacy Type',
        description: '17-Apr-2020',
        price: '17-Apr-2022',
        minMember: '17-Apr-2020',
        maxMember: '17-Apr-2022',
        limit: 'Lorem Ipsum is simply text of the printing simply text',
      },
      {
        name: 'Privacy Type',
        description: '17-Apr-2020',
        price: '17-Apr-2022',
        minMember: '17-Apr-2020',
        maxMember: '17-Apr-2022',
        limit: 'Lorem Ipsum is simply text of the printing simply text',
      },
      {
        name: 'Privacy Type',
        description: '17-Apr-2020',
        price: '17-Apr-2022',
        minMember: '17-Apr-2020',
        maxMember: '17-Apr-2022',
        limit: 'Lorem Ipsum is simply text of the printing simply text',
      },
    ],
  },
  tableDataPayments: {
    heads: [
      {
        name: 'Name',
        key: 'name',
        type: 'text',
      },
      {
        name: '#of Slots',
        key: 'slots',
        type: 'text',
      },
      {
        name: 'Payment',
        key: 'payment',
        type: 'text',
      },
      {
        name: 'Date',
        key: 'date',
        type: 'text',
      },
    ],
    rows: [
      {
        name: 'John Alam',
        slots: 'Lorem Ipsum is simply dummy text of the printing.',
        payment: '$35.99',
        date: '13-Jun-2022',
      },
      {
        name: 'John Alam',
        slots: 'Lorem Ipsum is simply dummy text of the printing.',
        payment: '$35.99',
        date: '13-Jun-2022',
      },
      {
        name: 'John Alam',
        slots: 'Lorem Ipsum is simply dummy text of the printing.',
        payment: '$35.99',
        date: '13-Jun-2022',
      },
      {
        name: 'John Alam',
        slots: 'Lorem Ipsum is simply dummy text of the printing.',
        payment: '$35.99',
        date: '13-Jun-2022',
      },
      {
        name: 'John Alam',
        slots: 'Lorem Ipsum is simply dummy text of the printing.',
        payment: '$35.99',
        date: '13-Jun-2022',
      },
    ],
  },
})
